"""Add fields to Movie model

Revision ID: a84346ef40a8
Revises: 
Create Date: 2024-10-01 12:09:59.652973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84346ef40a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overview', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('poster_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('poster_path')
        batch_op.drop_column('release_date')
        batch_op.drop_column('overview')

    # ### end Alembic commands ###
